import { CustomerFormData, Invoice, Product } from "@/types";

export const customers: CustomerFormData[] = [
    {
        name: "Alice Johnson",
        email: "alice.johnson@example.com",
        phone: "+1 (555) 234-5678",
        address: "123 Maple Street, Denver, CO",
        notes: "Prefers email contact"
    },
    {
        name: "Brian Lee",
        email: "brian.lee@example.com",
        phone: "+1 (555) 876-4321",
        address: "45 Ocean Drive, Miami, FL",
        notes: "Interested in premium plan"
    },
    {
        name: "Carla Mendes",
        email: "carla.mendes@example.com",
        phone: "+1 (555) 654-3210",
        address: "78 Hilltop Ave, Austin, TX",
        notes: "Referred by Alice Johnson"
    },
    {
        name: "David Chen",
        email: "david.chen@example.com",
        phone: "+1 (555) 901-2233",
        address: "502 Sunset Blvd, Los Angeles, CA",
        notes: "Requests invoice via email"
    },
    {
        name: "Ella Fitzgerald",
        email: "ella.fitzgerald@example.com",
        phone: "+1 (555) 321-7654",
        address: "11 River Road, Chicago, IL",
        notes: "VIP customer"
    },
    {
        name: "Felix Martinez",
        email: "felix.martinez@example.com",
        phone: "+1 (555) 112-9988",
        address: "77 Beacon Street, Boston, MA",
        notes: "Speaks Spanish"
    },
    {
        name: "Grace Kim",
        email: "grace.kim@example.com",
        phone: "+1 (555) 445-8899",
        address: "89 Elm Street, Seattle, WA",
        notes: "Requested callback next week"
    },
    {
        name: "Hassan Ali",
        email: "hassan.ali@example.com",
        phone: "+1 (555) 987-6543",
        address: "230 Pine Avenue, Houston, TX",
        notes: "Follow up after 5 PM"
    },
    {
        name: "Ivy Thompson",
        email: "ivy.thompson@example.com",
        phone: "+1 (555) 778-9900",
        address: "90 Brookside Lane, Portland, OR",
        notes: "Interested in newsletter"
    },
    {
        name: "Jake Williams",
        email: "jake.williams@example.com",
        phone: "+1 (555) 667-3344",
        address: "12 Park Avenue, New York, NY",
        notes: "Long-term client"
    },

];

export const invoices: Invoice[] = [
    {
        id: "inv_001",
        userId: "user_001",
        customerId: "cust_001",
        invoiceNumber: "INV-2025-001",
        status: "PAID",
        dueDate: new Date("2025-09-15"),
        totalAmount: 2499.97,
        createdAt: new Date("2025-09-01"),
        updatedAt: new Date("2025-09-15"),
        items: [
            {
                id: "item_001",
                invoiceId: "inv_001",
                productId: "prod_laptop_001",
                description: "MacBook Pro 14-inch (M3, 16GB RAM, 512GB SSD)",
                quantity: 1,
                unitPrice: 1999.99,
                lineTotal: 1999.99,
                createdAt: new Date("2025-09-01"),
                updatedAt: new Date("2025-09-01"),
            },
            {
                id: "item_002",
                invoiceId: "inv_001",
                productId: "prod_setup_001",
                description: "Device setup & data migration fee",
                quantity: 1,
                unitPrice: 499.98,
                lineTotal: 499.98,
                createdAt: new Date("2025-09-01"),
                updatedAt: new Date("2025-09-01"),
            },
        ],
    },
    {
        id: "inv_002",
        userId: "user_001",
        customerId: "cust_002",
        invoiceNumber: "INV-2025-002",
        status: "SENT",
        dueDate: new Date("2025-10-10"),
        totalAmount: 1349.97,
        createdAt: new Date("2025-09-25"),
        updatedAt: new Date("2025-09-30"),
        items: [
            {
                id: "item_003",
                invoiceId: "inv_002",
                productId: "prod_phone_001",
                description: "iPhone 15 Pro (128GB)",
                quantity: 1,
                unitPrice: 999.99,
                lineTotal: 999.99,
                createdAt: new Date("2025-09-25"),
                updatedAt: new Date("2025-09-25"),
            },
            {
                id: "item_004",
                invoiceId: "inv_002",
                productId: "prod_case_001",
                description: "Protective phone case",
                quantity: 1,
                unitPrice: 49.99,
                lineTotal: 49.99,
                createdAt: new Date("2025-09-25"),
                updatedAt: new Date("2025-09-25"),
            },
            {
                id: "item_005",
                invoiceId: "inv_002",
                productId: "prod_setup_002",
                description: "Device setup service",
                quantity: 1,
                unitPrice: 299.99,
                lineTotal: 299.99,
                createdAt: new Date("2025-09-25"),
                updatedAt: new Date("2025-09-25"),
            },
        ],
    },
    {
        id: "inv_003",
        userId: "user_002",
        customerId: "cust_004",
        invoiceNumber: "INV-2025-003",
        status: "OVERDUE",
        dueDate: new Date("2025-09-10"),
        totalAmount: 2198.00,
        createdAt: new Date("2025-08-20"),
        updatedAt: new Date("2025-09-20"),
        items: [
            {
                id: "item_006",
                invoiceId: "inv_003",
                productId: "prod_laptop_002",
                description: "Dell XPS 13 (13-inch, Intel i7, 16GB RAM)",
                quantity: 1,
                unitPrice: 1499.00,
                lineTotal: 1499.00,
                createdAt: new Date("2025-08-20"),
                updatedAt: new Date("2025-08-20"),
            },
            {
                id: "item_007",
                invoiceId: "inv_003",
                productId: "prod_mouse_001",
                description: "Logitech MX Master 3S Wireless Mouse",
                quantity: 1,
                unitPrice: 99.00,
                lineTotal: 99.00,
                createdAt: new Date("2025-08-20"),
                updatedAt: new Date("2025-08-20"),
            },
            {
                id: "item_008",
                invoiceId: "inv_003",
                productId: "prod_monitor_001",
                description: "LG Ultrawide 34'' Monitor",
                quantity: 1,
                unitPrice: 600.00,
                lineTotal: 600.00,
                createdAt: new Date("2025-08-20"),
                updatedAt: new Date("2025-08-20"),
            },
        ],
    },
    {
        id: "inv_004",
        userId: "user_003",
        customerId: "cust_005",
        invoiceNumber: "INV-2025-004",
        status: "DRAFT",
        dueDate: new Date("2025-11-15"),
        totalAmount: 749.98,
        createdAt: new Date("2025-10-25"),
        updatedAt: new Date("2025-10-25"),
        items: [
            {
                id: "item_009",
                invoiceId: "inv_004",
                productId: "prod_tablet_001",
                description: "Samsung Galaxy Tab S9",
                quantity: 1,
                unitPrice: 699.99,
                lineTotal: 699.99,
                createdAt: new Date("2025-10-25"),
                updatedAt: new Date("2025-10-25"),
            },
            {
                id: "item_010",
                invoiceId: "inv_004",
                productId: "prod_cable_001",
                description: "USB-C charging cable",
                quantity: 1,
                unitPrice: 49.99,
                lineTotal: 49.99,
                createdAt: new Date("2025-10-25"),
                updatedAt: new Date("2025-10-25"),
            },
        ],
    },
    {
        id: "inv_005",
        userId: "user_002",
        customerId: "cust_006",
        invoiceNumber: "INV-2025-005",
        status: "PAID",
        dueDate: new Date("2025-10-05"),
        totalAmount: 899.98,
        createdAt: new Date("2025-09-20"),
        updatedAt: new Date("2025-10-05"),
        items: [
            {
                id: "item_011",
                invoiceId: "inv_005",
                productId: "prod_phone_002",
                description: "Google Pixel 9 Pro (128GB)",
                quantity: 1,
                unitPrice: 899.98,
                lineTotal: 899.98,
                createdAt: new Date("2025-09-20"),
                updatedAt: new Date("2025-09-20"),
            },
        ],
    },
    {
        id: "inv_006",
        userId: "user_002",
        customerId: "cust_007",
        invoiceNumber: "INV-2025-006",
        status: "SENT",
        dueDate: new Date("2025-11-01"),
        totalAmount: 1249.00,
        createdAt: new Date("2025-10-01"),
        updatedAt: new Date("2025-10-15"),
        items: [
            {
                id: "item_012",
                invoiceId: "inv_006",
                productId: "prod_laptop_003",
                description: "HP Spectre x360 (13-inch, Intel i5, 16GB RAM)",
                quantity: 1,
                unitPrice: 1249.00,
                lineTotal: 1249.00,
                createdAt: new Date("2025-10-01"),
                updatedAt: new Date("2025-10-01"),
            },
        ],
    },
    {
        id: "inv_007",
        userId: "user_003",
        customerId: "cust_008",
        invoiceNumber: "INV-2025-007",
        status: "OVERDUE",
        dueDate: new Date("2025-09-10"),
        totalAmount: 429.97,
        createdAt: new Date("2025-08-25"),
        updatedAt: new Date("2025-09-20"),
        items: [
            {
                id: "item_013",
                invoiceId: "inv_007",
                productId: "prod_router_001",
                description: "Asus RT-AX88U WiFi 6 Router",
                quantity: 1,
                unitPrice: 329.99,
                lineTotal: 329.99,
                createdAt: new Date("2025-08-25"),
                updatedAt: new Date("2025-08-25"),
            },
            {
                id: "item_014",
                invoiceId: "inv_007",
                productId: "prod_cable_002",
                description: "Ethernet Cat 6 Cable (10ft)",
                quantity: 2,
                unitPrice: 49.99,
                lineTotal: 99.98,
                createdAt: new Date("2025-08-25"),
                updatedAt: new Date("2025-08-25"),
            },
        ],
    },
    {
        id: "inv_008",
        userId: "user_001",
        customerId: "cust_009",
        invoiceNumber: "INV-2025-008",
        status: "DRAFT",
        dueDate: new Date("2025-11-20"),
        totalAmount: 1599.00,
        createdAt: new Date("2025-10-15"),
        updatedAt: new Date("2025-10-20"),
        items: [
            {
                id: "item_015",
                invoiceId: "inv_008",
                productId: "prod_laptop_004",
                description: "Lenovo ThinkPad X1 Carbon (i7, 16GB, 512GB)",
                quantity: 1,
                unitPrice: 1599.00,
                lineTotal: 1599.00,
                createdAt: new Date("2025-10-15"),
                updatedAt: new Date("2025-10-15"),
            },
        ],
    },
    {
        id: "inv_009",
        userId: "user_003",
        customerId: "cust_010",
        invoiceNumber: "INV-2025-009",
        status: "SENT",
        dueDate: new Date("2025-10-28"),
        totalAmount: 2148.98,
        createdAt: new Date("2025-10-10"),
        updatedAt: new Date("2025-10-20"),
        items: [
            {
                id: "item_016",
                invoiceId: "inv_009",
                productId: "prod_phone_003",
                description: "Samsung Galaxy S24 Ultra",
                quantity: 1,
                unitPrice: 1349.99,
                lineTotal: 1349.99,
                createdAt: new Date("2025-10-10"),
                updatedAt: new Date("2025-10-10"),
            },
            {
                id: "item_017",
                invoiceId: "inv_009",
                productId: "prod_watch_001",
                description: "Samsung Galaxy Watch 6",
                quantity: 1,
                unitPrice: 799.00,
                lineTotal: 799.00,
                createdAt: new Date("2025-10-10"),
                updatedAt: new Date("2025-10-10"),
            },
        ],
    },
    {
        id: "inv_010",
        userId: "user_001",
        customerId: "cust_003",
        invoiceNumber: "INV-2025-010",
        status: "PAID",
        dueDate: new Date("2025-09-20"),
        totalAmount: 299.99,
        createdAt: new Date("2025-09-01"),
        updatedAt: new Date("2025-09-15"),
        items: [
            {
                id: "item_018",
                invoiceId: "inv_010",
                productId: "prod_headphones_001",
                description: "Sony WH-1000XM5 Noise Cancelling Headphones",
                quantity: 1,
                unitPrice: 299.99,
                lineTotal: 299.99,
                createdAt: new Date("2025-09-01"),
                updatedAt: new Date("2025-09-01"),
            },
        ],
    },
];


export const products: Product[] = [
    {
        id: "prod_laptop_001",
        userId: "user_001",
        name: "MacBook Pro 14-inch (M3, 16GB RAM, 512GB SSD)",
        sku: "MBP14-M3-512",
        description: "Apple MacBook Pro 14-inch laptop with M3 chip and 512GB SSD.",
        unitPrice: 1999.99,
        stockQuantity: 12,
        createdAt: new Date("2025-09-01"),
        updatedAt: new Date("2025-09-10"),
    },
    {
        id: "prod_setup_001",
        userId: "user_001",
        name: "Device Setup & Data Migration",
        sku: "SETUP-001",
        description: "Professional setup, OS configuration, and data migration service.",
        unitPrice: 499.99,
        stockQuantity: 999,
        createdAt: new Date("2025-09-01"),
        updatedAt: new Date("2025-09-10"),
    },
    {
        id: "prod_phone_001",
        userId: "user_001",
        name: "iPhone 15 Pro (128GB)",
        sku: "IPH15P-128",
        description: "Apple iPhone 15 Pro smartphone with 128GB storage.",
        unitPrice: 999.99,
        stockQuantity: 20,
        createdAt: new Date("2025-09-25"),
        updatedAt: new Date("2025-09-30"),
    },
    {
        id: "prod_case_001",
        userId: "user_001",
        name: "Protective Phone Case",
        sku: "CASE-001",
        description: "Shock-absorbing silicone protective case for smartphones.",
        unitPrice: 49.99,
        stockQuantity: 100,
        createdAt: new Date("2025-09-25"),
        updatedAt: new Date("2025-09-30"),
    },
    {
        id: "prod_laptop_002",
        userId: "user_001",
        name: "Dell XPS 13 (Intel i7, 16GB RAM, 512GB SSD)",
        sku: "DXPS13-I7-512",
        description: "Dell XPS 13 ultrabook with 13-inch display and Intel i7 processor.",
        unitPrice: 1499.00,
        stockQuantity: 15,
        createdAt: new Date("2025-08-20"),
        updatedAt: new Date("2025-09-20"),
    },
    {
        id: "prod_mouse_001",
        userId: "user_001",
        name: "Logitech MX Master 3S Wireless Mouse",
        sku: "MXM3S-001",
        description: "Ergonomic wireless mouse with multi-device Bluetooth connectivity.",
        unitPrice: 99.00,
        stockQuantity: 50,
        createdAt: new Date("2025-08-20"),
        updatedAt: new Date("2025-09-20"),
    },
    {
        id: "prod_monitor_001",
        userId: "user_001",
        name: "LG Ultrawide 34'' Monitor",
        sku: "LGUW34-001",
        description: "LG 34-inch ultrawide monitor with 1440p resolution.",
        unitPrice: 600.00,
        stockQuantity: 8,
        createdAt: new Date("2025-08-20"),
        updatedAt: new Date("2025-09-20"),
    },
    {
        id: "prod_tablet_001",
        userId: "user_001",
        name: "Samsung Galaxy Tab S9",
        sku: "TAB-S9",
        description: "11-inch AMOLED Android tablet with S Pen support.",
        unitPrice: 699.99,
        stockQuantity: 25,
        createdAt: new Date("2025-10-25"),
        updatedAt: new Date("2025-10-25"),
    },
    {
        id: "prod_cable_001",
        userId: "user_001",
        name: "USB-C Charging Cable",
        sku: "CABLE-USBC-001",
        description: "Durable USB-C charging cable (1m length).",
        unitPrice: 49.99,
        stockQuantity: 150,
        createdAt: new Date("2025-10-25"),
        updatedAt: new Date("2025-10-25"),
    },
    {
        id: "prod_phone_002",
        userId: "user_001",
        name: "Google Pixel 9 Pro (128GB)",
        sku: "PIX9P-128",
        description: "Google Pixel 9 Pro with Android 15 and advanced camera features.",
        unitPrice: 899.98,
        stockQuantity: 18,
        createdAt: new Date("2025-09-20"),
        updatedAt: new Date("2025-09-20"),
    },
    {
        id: "prod_laptop_003",
        userId: "user_001",
        name: "HP Spectre x360 (Intel i5, 16GB RAM, 512GB SSD)",
        sku: "HPSP13-I5-512",
        description: "Convertible touchscreen laptop with long battery life.",
        unitPrice: 1249.00,
        stockQuantity: 10,
        createdAt: new Date("2025-10-01"),
        updatedAt: new Date("2025-10-01"),
    },
    {
        id: "prod_router_001",
        userId: "user_001",
        name: "Asus RT-AX88U WiFi 6 Router",
        sku: "ASUS-AX88U",
        description: "Dual-band WiFi 6 router with 8 LAN ports and advanced QoS.",
        unitPrice: 329.99,
        stockQuantity: 30,
        createdAt: new Date("2025-08-25"),
        updatedAt: new Date("2025-09-20"),
    },
    {
        id: "prod_cable_002",
        userId: "user_001",
        name: "Ethernet Cat 6 Cable (10ft)",
        sku: "ETH6-10FT",
        description: "High-speed Cat 6 Ethernet cable for wired connections.",
        unitPrice: 49.99,
        stockQuantity: 200,
        createdAt: new Date("2025-08-25"),
        updatedAt: new Date("2025-09-20"),
    },
    {
        id: "prod_laptop_004",
        userId: "user_001",
        name: "Lenovo ThinkPad X1 Carbon (i7, 16GB, 512GB)",
        sku: "LTPX1C-I7-512",
        description: "Business-grade ultrabook with ThinkPad durability.",
        unitPrice: 1599.00,
        stockQuantity: 12,
        createdAt: new Date("2025-10-15"),
        updatedAt: new Date("2025-10-20"),
    },
    {
        id: "prod_phone_003",
        userId: "user_001",
        name: "Samsung Galaxy S24 Ultra",
        sku: "SGS24U-256",
        description: "Samsung flagship smartphone with 200MP camera and S Pen support.",
        unitPrice: 1349.99,
        stockQuantity: 22,
        createdAt: new Date("2025-10-10"),
        updatedAt: new Date("2025-10-20"),
    },
    {
        id: "prod_watch_001",
        userId: "user_001",
        name: "Samsung Galaxy Watch 6",
        sku: "SGW6-001",
        description: "Smartwatch with fitness tracking, GPS, and long battery life.",
        unitPrice: 799.00,
        stockQuantity: 40,
        createdAt: new Date("2025-10-10"),
        updatedAt: new Date("2025-10-20"),
    },
    {
        id: "prod_headphones_001",
        userId: "user_001",
        name: "Sony WH-1000XM5 Noise Cancelling Headphones",
        sku: "SONYXM5-001",
        description: "Industry-leading noise-cancelling wireless headphones.",
        unitPrice: 299.99,
        stockQuantity: 35,
        createdAt: new Date("2025-09-01"),
        updatedAt: new Date("2025-09-15"),
    },
]


export async function seedData() {
    const response = await fetch('/api/seed', {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json',
        }
    })

    if (!response.ok) {
        const error = await response.json()
        throw new Error(error.error || 'Failed to add customer')
    }

    return response.json()
}